### ISSUE TITLE
效果好像有待改善

### ISSUE THREAD

**Issue by zhaoyun0071** [TencentARC/ColorFlow#3]
灰度图模式，有的上不了色。

![Honeyview_image (1)](https://github.com/user-attachments/assets/04b0c244-0f2d-49e1-86db-2ea8f66f64be)

线稿模式上色效果不错，但文字容易花。

**Comment by zhuang2002** [comment]
Thank you for your interest and suggestions! Here are a few clarifications regarding your questions:

Currently, ColorFlow has open-sourced two weights: **GrayImage (ScreenStyle)** and **Sketch**.

1. **GrayImage** is designed for processing images with continuous grayscale, maintaining the brightness of the reference image (the one to be colored) quite faithfully. The image you uploaded has distinct light and dark areas, which is why it retains the original brightness, resulting in only black and white. You can find examples of suitable input image types for the GrayImage weight in the demo.

2. The **Sketch** model is intended for handling line art inputs.

3. The blurriness of text in images is due to the VAE used in the SD 1.5 model, which can result in unclear text. However, our GSRP module helps mitigate this issue.

4. ColorFlow colors images based on the characters in the reference image, so it's best if the reference contains relevant characters.

5. Additionally, we will soon release another weight for handling line art combined with shading and shadows, which we’ve named the **Sketch+Shaded** version.

I manually cropped your image **(noting that the edges of the text in the original image are somewhat unclear)** and used our Sketch+Shaded version for coloring, without cherry-picking, resulting in the following output:

![image](https://github.com/user-attachments/assets/48b23c06-866e-4ef1-a767-bdd2e46a382f)
![image](https://github.com/user-attachments/assets/ea089dd9-a740-46f5-bc2a-f46125875174)


Lastly, we are pioneering the task of **fine-grained ID preservation in image sequence colorization**. ColorFlow is our first attempt, and we will continue to improve our model. Stay tuned for more updates!

**Comment by zhaoyun0071** [comment]
> 感谢您的关注和建议！以下是关于您的问题的一些澄清：
> 
> 目前，ColorFlow 已经开源了两个粗细：**GrayImage（ScreenStyle）**和 **Sketch**。
> 
> 1. **GrayImage** 设计用于处理具有连续灰度的图像，非常忠实地保持参考图像（要着色的图像）的亮度。您上传的图像具有明显的明暗区域，这就是为什么它保持原始亮度，导致只有黑白的原因。您可以在演示中找到适合 GrayImage 权重的输入图像类型的示例。
> 2. **Sketch** 模型用于处理线条艺术输入。
> 3. 图像中文本的模糊是由于 SD 1.5 型号中使用的 VAE 造成的，这可能会导致文本不清晰。但是，我们的 GSRP 模块有助于缓解此问题。
> 4. ColorFlow 根据参考图像中的字符为图像着色，因此最好参考包含相关字符。
> 5. 此外，我们很快将发布另一种用于处理线条图与阴影相结合的粗细，我们将其命名为 **Sketch + Shaded** 版本。
> 
> 我手动裁剪了您的图像**（注意原始图像中文本的边缘有些不清晰），**并使用我们的 Sketch+Shaded 版本进行着色，没有进行挑剔，结果如下：
> 
> ![image](https://private-user-images.githubusercontent.com/108931120/397906053-48b23c06-866e-4ef1-a767-bdd2e46a382f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NjA0MTEsIm5iZiI6MTczNDc2MDExMSwicGF0aCI6Ii8xMDg5MzExMjAvMzk3OTA2MDUzLTQ4YjIzYzA2LTg2NmUtNGVmMS1hNzY3LWJkZDJlNDZhMzgyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQwNTQ4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWMwMWIxMmIwMDM1NTdmNTY5MDYyYmU1YjdhMzU2Y2U3NGRlYmY3YjQzY2NhNmY1OGE5OWY4ZWMyODFjNTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KQZCEXFekuHWMd9v7-uUobgRuMerykkg8ZUZSzSAR8M) ![image](https://private-user-images.githubusercontent.com/108931120/397906076-ea089dd9-a740-46f5-bc2a-f46125875174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NjA0MTEsIm5iZiI6MTczNDc2MDExMSwicGF0aCI6Ii8xMDg5MzExMjAvMzk3OTA2MDc2LWVhMDg5ZGQ5LWE3NDAtNDZmNS1iYzJhLWY0NjEyNTg3NTE3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQwNTQ4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGQzYTI2Mzg0MjI0YjUwYTg4YTY1MzAwZjgzOTljZjkxOWJlOTE0NDc3ODMyODEzZDJmYjhjMTg5MGRhYjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Z7FB7QWvETUHzQeEyE3n_bL3htsxcqb2n857Ooi9DN0)
> 
> 最后，我们正在开创**图像序列着色中精细 ID 保留**的任务。ColorFlow 是我们的第一次尝试，我们将继续改进我们的模型。请继续关注更多更新！

谢谢，期待你们的新模型
